### ISSUE TITLE
imgui version mismatch causes  GW2-ArcDPS-Boon-Table to not be loaded by ArcDPS

### ISSUE THREAD

**Issue by Almdoodler** [MarsEdge/GW2-ArcDPS-Boon-Table#4]
**Version/Branch of GW2-ArcDPS-Boon-Table:**

Version: final
Branch: master

**Issue:**

As of  the February 23rd update for ArcDPS it won't load addons that uses outdated versions (any version lower than 1.80) of the imgui library. Updating imgui from the current version (1.50) to the required version (or higher) will likely result in the need of rewrites of some parts of this addon as the Boon Table addon uses several now out of date functions. In a quick test I did, where I updated the imgui version to 1.80, there were over 100 of instances of unresolved external symbols reported back by VS2017. 

I'm adding this issue here because I'm rusty and not well versed in C/C++ and have no experience with the imgui library at all. As this addon is (at least to my knowledge) the only one providing this functionality I'd be grateful to anyone that can resolve this issue.

Thanks in advance,
Almdoodler

**Comment by MarsEdge** [comment]
Check the top of the readme

**Comment by Almdoodler** [comment]
Wups, must have overread it, Sorry for the inconvenience
